%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#ffcccc', 'edgeLabelBackground':'#ffffff', 'tertiaryColor': '#fff'}}}%%
flowchart LR
    classDef source stroke:#00f,fill:#0ff,color:black
    classDef target stroke:#0f0,fill:#0fa,color:black
    
    sample_table:::source    
    subgraph sample_table
        sample_table.id[id]
        sample_table.name[name]
        sample_table.age[age]
    end

    sample_table_2:::source
    subgraph sample_table_2
        sample_table_2.id[id]
        sample_table_2.name[name]
        sample_table_2.birth_date[birth_date]
    end

    target:::target
    subgraph target
        target.id[id]
        target.name[name]
        target.age[age]
        target.birth_date[birth_date]
    end

    sample_table.id -- column, filter, join key --> target.id
    sample_table_2.id -- join key --> target.id
    sample_table.id -- filter, join key --> target.name
    sample_table.name -- column --> target.name
    sample_table_2.id -- filter, join key --> target.name
    sample_table_2.name -- column --> target.name
    sample_table.id -- filter, join key --> target.age
    sample_table.age -- column --> target.age
    sample_table_2.id -- filter, join key --> target.age
    sample_table.id -- filter, join key --> target.birth_date
    sample_table_2.birth_date -- column --> target.birth_date
    sample_table_2.id -- filter, join key --> target.birth_date
